### ISSUE TITLE
Detecting language

### ISSUE THREAD

**Issue by bugproof** [zedseven/Romanization.NET#2]
Text from user inputs can be in any language, can Romanization.NET detect which is Korean or Russian etc. and which is currently unknown by the library?

The library assumes that you know the language of a string. It would be neat if it supported the romanization of all supported languages using a single class e.g. name it `Romanizer`

**Comment by zedseven** [comment]
Romanization.NET cannot detect the string language. Running romanization for all languages would be an expensive process, and it would be messy in the case of overlapping use of characters between languages.

Additionally, each language can have multiple romanization systems, each with their own use cases. For example, Russian's GOST 7.79-2000 System A is designed to map one Cyrillic character to one Latin character, using diacritics if necessary. In contrast, GOST 7.79-2000 System B is designed to not use any diacritics but use potentially multiple Latin characters for each Cyrillic one. These both have their advantages and disadvantages, and there's no clear default.

For the project I've used this library with in the past, I used [NTextCat](https://github.com/ivanakcheurov/ntextcat) to determine the language of the text, then romanized it as necessary. The problem of language classification is a large one, and mostly out of the scope of this project.

If you want an example of how I used NTextCat with this library, [take a look here](https://github.com/zedseven/NusRipper/blob/6ebe1e80ed49bc832e602619cc2682b18ca92b45/NusRipper/Secondary/Language.cs#L171).
